name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
      
      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a modern LTS version of Node.js
          cache: 'npm'       # Enable caching for faster installs

      # Install dependencies
      - name: Install Dependencies
        env:
          CI: true
        run: npm ci

      # Add more deployment or build steps here
